language: c
sudo: required

before_install:
    - sudo apt-get clean && sudo apt-get update
    - sudo apt-get install gcc gfortran libopenmpi-dev
    - sudo apt-get install hdf5-tools libhdf5-dev
    - which gfortran
    - which gcc
    - which h5dump
    - find /usr -name libhdf5*

script:
    - pwd
    - cd ED/build/
    - ./install.sh -k C -p travisci -g -c
    - ./install.sh -k C -p travisci -g
